on:
  push:
    branches:
      - dev

name: dev tests

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install Clojure cli
        id: install-clojure-cli
        run: curl -O https://download.clojure.org/install/linux-install-1.10.1.462.sh && chmod +x linux-install-1.10.1.462.sh && sudo ./linux-install-1.10.1.462.sh

      - name: Elasticsearch integration test
        id: es-test
        env:
          ELASTIC_URL: "http://localhost:9200/"
        run: dev/test.sh
