on:
  push:
    branches:
      - master

name: Build and Deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: test clj
        id: clj-exists-p
        run: clj -A:uberjar -e '(println "success")'
  
