on:
  push:
    branches:
      - master

name: Build and Deploy

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: setup
        id: install-clojure-cli
        run: curl -O https://download.clojure.org/install/linux-install-1.10.1.462.sh && chmod +x linux-install-1.10.1.462.sh && ./linux-install-1.10.1.462.sh

      - name: test clj
        id: clj-exists-p
        run: clojure -A:uberjar -e '(println "success")'
  
